version: "3.9"

services:
  broker:
    container_name: "broker-message"
    image: broker
    ports:
      - "8001:8001"

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    links:
      - node-exporter
      - broker

  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    links:
      - prometheus

  node-exporter:
    container_name: "node-exporter"
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: unless-stopped