version: "3.9"

services:
  broker:
    container_name: "broker-message"
    image: broker:latest
    ports:
      - "8001:8001"

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - "9595:9090"
    volumes:
      - ./prometheus-2.33.4.linux-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/etc/prometheus/
    restart: unless-stopped
#    links:
#      - broker

  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./data/grafana:/etc/grafana1/
    restart: unless-stopped
#    links:
#      - prometheus