version: "3.9"

services:
  broker:
    container_name: "broker-message"
    image: broker:latest
    ports:
      - "8001:8001"
      - "9091:9091"
    depends_on:
      - postgres

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus-2.33.4.linux-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/etc/prometheus/
    restart: unless-stopped
#    links:
#      - broker

  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/etc/grafana1/
    restart: unless-stopped
#    links:
#      - prometheus

  postgres:
    container_name: "postgresql"
    image: postgres:latest
    environment:
      POSTGRES_USER: mahdi
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"